project:
  type: website
  resources:
    - CNAME

execute:
  freeze: auto

website:
  title: "Andy Teucher"
  site-url: "https://andyteucher.ca"
  google-analytics:
    tracking-id: "G-57GYE4EX4G"
    anonymize-ip: true
  cookie-consent:
    type: express
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: packages.qmd
        text: R Packages
      - href: workshops.qmd
        text: Workshops
#     - href: shiny.qmd
#       text: Shiny Apps
    right:
#     - blog.qmd
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: [journal, style.scss]
    css: styles.css
    toc: true



